<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20200131122924 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql',
            'Migration can only be executed safely on "postgresql".');

        $this->addSql('CREATE TABLE kaufmanndigital_gdpr_cookieconsent_domain_model_consentlogentry (persistence_object_identifier VARCHAR(40) NOT NULL, consentdate TIMESTAMP NOT NULL, consentidentifier VARCHAR(255) NOT NULL, PRIMARY KEY (persistence_object_identifier));');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql', 'Migration can only be executed safely on "postgresql".');
        $this->addSql('DROP TABLE kaufmanndigital_gdpr_cookieconsent_domain_model_consentlogentry;');
    }
}
