'KaufmannDigital.GDPR.CookieConsent:Document.CookieSettingsPage':
  superTypes:
    'Neos.Neos:Document': true
  childNodes:
    cookieSettings:
      type: 'KaufmannDigital.GDPR.CookieConsent:Content.CookieSettings'
  ui:
    label: i18n
    icon: 'icon-cookie'
    group: 'cookies'

