Neos:
  Neos:
    nodeTypes:
      groups:
        cookies:
          position: 300
          label: 'Cookies'
          collapsed: true
    fusion:
      autoInclude:
        KaufmannDigital.GDPR.CookieConsent: true
    userInterface:
      translation:
        autoInclude:
          'KaufmannDigital.GDPR.CookieConsent':
            - 'NodeTypes/*'
  Flow:
    mvc:
      routes:
        KaufmannDigital.GDPR.CookieConsent:
          position: 'before Neos.Neos'

KaufmannDigital:
  GDPR:
    CookieConsent:
      siteCSSFilepath: null
      customCSSFilepath: null
      consentLogEnabled: false
      siteStyles: []
#        "rootNode name 1":
#          siteCSSFilepath: <link to css>
#          customCSSFilepath: <link to custom css>
#        "rootNode name 2":
#          siteCSSFilepath: <link to css>
#          customCSSFilepath: <link to custom css>
