Neos:
  Neos:
    nodeTypes:
      groups:
        cookies:
          position: 300
          label: 'Cookies'
          collapsed: true
    fusion:
      autoInclude:
        KaufmannDigital.GDPR.CookieConsent: true
  Flow:
    mvc:
      routes:
        KaufmannDigital.GDPR.CookieConsent:
          position: 'before Neos.Neos'

KaufmannDigital:
  GDPR:
    CookieConsent:
      siteCSSFilepath: null
      customCSSFilepath: null
