Neos:
  Neos:
    nodeTypes:
      groups:
        cookies:
          position: 300
          label: 'Cookies'
          collapsed: true
    fusion:
      autoInclude:
        KaufmannDigital.GDPR.CookieConsent: true
    userInterface:
      translation:
        autoInclude:
          'KaufmannDigital.GDPR.CookieConsent':
            - 'NodeTypes/*'
  Fusion:
    defaultContext:
      GTMConsents: 'KaufmannDigital\GDPR\CookieConsent\Eel\Helper\GTMConsentsHelper'

  Flow:
    mvc:
      routes:
        KaufmannDigital.GDPR.CookieConsent:
          position: 'before Neos.Neos'
