Neos:
  Neos:
    fusion:
      autoInclude:
        KaufmannDigital.GDPR.CookieConsent: true
  Flow:
    mvc:
      routes:
        KaufmannDigital.GDPR.CookieConsent:
          position: 'before Neos.Neos'

KaufmannDigital:
  GDPR:
    CookieConsent:
      customCSSFilepath: null
